1. Simulate any random rectangular matrix A.
- What is the rank and trace of A?
- What is the determinant of A?
- Can you invert A? How?
- How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?

In [7]:
# 1
import numpy as np

# Define rows and cols for the matrix
n_rows = 5
n_cols = 3

# Creating a random matrix
A_random_matrix = np.random.rand(n_rows,n_cols)

# Get Matrix Rank
rank = np.linalg.matrix_rank(A_random_matrix)
print("Matrix rank: ",rank)

# Get Matrix Trace
trace = np.trace(A_random_matrix)
print("Matrix Trace", trace)

# Get Matrix Determinant and Inverse, we can get it only for square matrix
if n_rows == n_cols:
    determinant = np.linalg.det(A_random_matrix)
    print("Matrix Determinant", determinant)
    inverse = np.linalg.inv(A_random_matrix)
    print("Matrix Inverse",inverse)
else:
    print("Matrix Determinant only can compute for square matrix")


# Get eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both? ##
AtA = A_random_matrix.T @ A_random_matrix
AAt = A_random_matrix @ A_random_matrix.T
    
eigenvalues_AtA, eigenvectors_AtA = np.linalg.eig(AtA)
eigenvalues_AAt, eigenvectors_AAt = np.linalg.eigh(AAt)
    
print("eigenvalues_AtA ",eigenvalues_AtA)
print("eigenvectors_AtA ",eigenvectors_AtA)
print("eigenvalues_AAt ",eigenvalues_AAt)
print("eigenvectors_AAt ",eigenvectors_AAt)   

Matrix rank:  3
Matrix Trace 1.6126194539223078
Matrix Determinant only can compute for square matrix
eigenvalues_AtA  [3.033651   0.52697607 0.13335799]
eigenvectors_AtA  [[ 0.63049226  0.73484547 -0.2499633 ]
 [ 0.50234372 -0.63180717 -0.59031389]
 [ 0.59171809 -0.24662085  0.76749453]]
eigenvalues_AAt  [7.22185939e-17 3.71870616e-16 1.33357993e-01 5.26976066e-01
 3.03365100e+00]
eigenvectors_AAt  [[ 0.28385977 -0.73597191  0.19068652  0.0408415  -0.58287185]
 [ 0.30988624  0.608703    0.24752415  0.46712201 -0.50396428]
 [-0.88882676 -0.02501316  0.33021214  0.14158702 -0.28332736]
 [-0.18050782 -0.03509464 -0.88351835  0.29724589 -0.31181005]
 [-0.02825023  0.2932042  -0.11280835 -0.81958953 -0.47831005]]
