1. Simulate any random rectangular matrix A.
- What is the rank and trace of A?
- What is the determinant of A?
- Can you invert A? How?
- How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?

In [1]:
import numpy as np

# 1
import numpy as np

# Define matrix rows and cols
n_rows = 5
n_cols = 3

# Creating a random matrix
A_random_matrix = np.random.rand(n_rows,n_cols)

# Get Matrix Rank
rank = np.linalg.matrix_rank(A_random_matrix)
print("Matrix rank: ",rank)

# Get Matrix Trace
trace = np.trace(A_random_matrix)
print("Matrix Trace", trace)

# Get Matrix Determinant and Inverse, we can get it only for square matrix
if n_rows == n_cols:
    determinant = np.linalg.det(A_random_matrix)
    print("Matrix Determinant", determinant)
    inverse = np.linalg.inv(A_random_matrix)
    print("Matrix Inverse",inverse)
else:
    print("Matrix Determinant only can compute for square matrix")


# Get eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both? ##
AtransposedxA = A_random_matrix.T.dot(A_random_matrix)
AxAtransposed = A_random_matrix.dot(A_random_matrix.T)
    
eigval_AtransposedxA, eigvec_AtransposedxA = np.linalg.eig(AtransposedxA)
eigval_AxAtransposed, eigvec_AxAtransposed = np.linalg.eigh(AxAtransposed)
    
print("\n eigenvectors of A’A \n",eigvec_AtransposedxA)
print("\n eigenvectors of AA’ \n",eigvec_AxAtransposed)
print("\n eigenvalues of A’A \n",eigval_AtransposedxA)
print("\n eigenvalues of AA' \n",eigval_AxAtransposed)   

print("\nEigenvectos and eigenvalues for both A'A and AA' are related because their come from dot product of the same matrix  \n")
print("An interesting diferences,  A’A correspond to matrix cols size and AA' correspond to matrix rows size \n")

Matrix rank:  3
Matrix Trace 1.425423171686196
Matrix Determinant only can compute for square matrix

 eigenvectors of A’A 
 [[ 0.59289208  0.80274648 -0.06385199]
 [ 0.48177661 -0.41712895 -0.77064566]
 [ 0.6452676  -0.42614731  0.63405693]]

 eigenvectors of AA’ 
 [[-0.32108603  0.55207745  0.46588512  0.53603397 -0.29619737]
 [ 0.3202572   0.44413646 -0.69947044  0.09392932 -0.44955146]
 [ 0.62314193 -0.15676279  0.50522729 -0.20241775 -0.53934404]
 [-0.57551306  0.09337987 -0.0090384  -0.67928052 -0.44560207]
 [-0.27352867 -0.68165895 -0.19584647  0.44883171 -0.46980571]]

 eigenvalues of A’A 
 [5.6321058  0.09676125 0.66183057]

 eigenvalues of AA' 
 [-1.91272869e-17  3.03621937e-16  9.67612533e-02  6.61830570e-01
  5.63210580e+00]

Eigenvectos and eigenvalues for both A'A and AA' are related because their come from dot product of the same matrix  

An interesting diferences,  A’A correspond to matrix cols size and AA' correspond to matrix rows size 

